/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as DemoOrpcTodoRouteImport } from './routes/demo/orpc-todo'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as ProtectedTodosRouteImport } from './routes/_protected/todos'
import { Route as ProtectedSubjectsIndexRouteImport } from './routes/_protected/subjects/index'
import { Route as ProtectedCoursesIndexRouteImport } from './routes/_protected/courses/index'
import { Route as ProtectedClassesIndexRouteImport } from './routes/_protected/classes/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ProtectedSubjectsSubjectIdRouteImport } from './routes/_protected/subjects/$subjectId'
import { Route as ProtectedCoursesCourseIdRouteImport } from './routes/_protected/courses/$courseId'
import { Route as ProtectedClassesClassIdRouteImport } from './routes/_protected/classes/$classId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ProtectedCoursesCourseIdLessonsLessonProgressIdRouteImport } from './routes/_protected/courses/$courseId/lessons/$lessonProgressId'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrpcTodoRoute = DemoOrpcTodoRouteImport.update({
  id: '/demo/orpc-todo',
  path: '/demo/orpc-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTodosRoute = ProtectedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSubjectsIndexRoute = ProtectedSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoursesIndexRoute = ProtectedCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClassesIndexRoute = ProtectedClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => ProtectedRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSubjectsSubjectIdRoute =
  ProtectedSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCoursesCourseIdRoute =
  ProtectedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClassesClassIdRoute = ProtectedClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => ProtectedRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCoursesCourseIdLessonsLessonProgressIdRoute =
  ProtectedCoursesCourseIdLessonsLessonProgressIdRouteImport.update({
    id: '/lessons/$lessonProgressId',
    path: '/lessons/$lessonProgressId',
    getParentRoute: () => ProtectedCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/resources': typeof ResourcesRoute
  '/todos': typeof ProtectedTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/classes/$classId': typeof ProtectedClassesClassIdRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdRouteWithChildren
  '/subjects/$subjectId': typeof ProtectedSubjectsSubjectIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/classes/': typeof ProtectedClassesIndexRoute
  '/courses/': typeof ProtectedCoursesIndexRoute
  '/subjects/': typeof ProtectedSubjectsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/courses/$courseId/lessons/$lessonProgressId': typeof ProtectedCoursesCourseIdLessonsLessonProgressIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/resources': typeof ResourcesRoute
  '/todos': typeof ProtectedTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/classes/$classId': typeof ProtectedClassesClassIdRoute
  '/courses/$courseId': typeof ProtectedCoursesCourseIdRouteWithChildren
  '/subjects/$subjectId': typeof ProtectedSubjectsSubjectIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/classes': typeof ProtectedClassesIndexRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/subjects': typeof ProtectedSubjectsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/courses/$courseId/lessons/$lessonProgressId': typeof ProtectedCoursesCourseIdLessonsLessonProgressIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/resources': typeof ResourcesRoute
  '/_protected/todos': typeof ProtectedTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/orpc-todo': typeof DemoOrpcTodoRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/classes/$classId': typeof ProtectedClassesClassIdRoute
  '/_protected/courses/$courseId': typeof ProtectedCoursesCourseIdRouteWithChildren
  '/_protected/subjects/$subjectId': typeof ProtectedSubjectsSubjectIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_protected/classes/': typeof ProtectedClassesIndexRoute
  '/_protected/courses/': typeof ProtectedCoursesIndexRoute
  '/_protected/subjects/': typeof ProtectedSubjectsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/_protected/courses/$courseId/lessons/$lessonProgressId': typeof ProtectedCoursesCourseIdLessonsLessonProgressIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/resources'
    | '/todos'
    | '/demo/clerk'
    | '/demo/orpc-todo'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/classes/$classId'
    | '/courses/$courseId'
    | '/subjects/$subjectId'
    | '/api/rpc/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/classes/'
    | '/courses/'
    | '/subjects/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/courses/$courseId/lessons/$lessonProgressId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/resources'
    | '/todos'
    | '/demo/clerk'
    | '/demo/orpc-todo'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/classes/$classId'
    | '/courses/$courseId'
    | '/subjects/$subjectId'
    | '/api/rpc/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/classes'
    | '/courses'
    | '/subjects'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/courses/$courseId/lessons/$lessonProgressId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/resources'
    | '/_protected/todos'
    | '/demo/clerk'
    | '/demo/orpc-todo'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_protected/classes/$classId'
    | '/_protected/courses/$courseId'
    | '/_protected/subjects/$subjectId'
    | '/api/rpc/$'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_protected/classes/'
    | '/_protected/courses/'
    | '/_protected/subjects/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/_protected/courses/$courseId/lessons/$lessonProgressId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  ResourcesRoute: typeof ResourcesRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoOrpcTodoRoute: typeof DemoOrpcTodoRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orpc-todo': {
      id: '/demo/orpc-todo'
      path: '/demo/orpc-todo'
      fullPath: '/demo/orpc-todo'
      preLoaderRoute: typeof DemoOrpcTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/todos': {
      id: '/_protected/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof ProtectedTodosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/subjects/': {
      id: '/_protected/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof ProtectedSubjectsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/': {
      id: '/_protected/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof ProtectedCoursesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classes/': {
      id: '/_protected/classes/'
      path: '/classes'
      fullPath: '/classes/'
      preLoaderRoute: typeof ProtectedClassesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/subjects/$subjectId': {
      id: '/_protected/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof ProtectedSubjectsSubjectIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$courseId': {
      id: '/_protected/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof ProtectedCoursesCourseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/classes/$classId': {
      id: '/_protected/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ProtectedClassesClassIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/courses/$courseId/lessons/$lessonProgressId': {
      id: '/_protected/courses/$courseId/lessons/$lessonProgressId'
      path: '/lessons/$lessonProgressId'
      fullPath: '/courses/$courseId/lessons/$lessonProgressId'
      preLoaderRoute: typeof ProtectedCoursesCourseIdLessonsLessonProgressIdRouteImport
      parentRoute: typeof ProtectedCoursesCourseIdRoute
    }
  }
}

interface ProtectedCoursesCourseIdRouteChildren {
  ProtectedCoursesCourseIdLessonsLessonProgressIdRoute: typeof ProtectedCoursesCourseIdLessonsLessonProgressIdRoute
}

const ProtectedCoursesCourseIdRouteChildren: ProtectedCoursesCourseIdRouteChildren =
  {
    ProtectedCoursesCourseIdLessonsLessonProgressIdRoute:
      ProtectedCoursesCourseIdLessonsLessonProgressIdRoute,
  }

const ProtectedCoursesCourseIdRouteWithChildren =
  ProtectedCoursesCourseIdRoute._addFileChildren(
    ProtectedCoursesCourseIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedTodosRoute: typeof ProtectedTodosRoute
  ProtectedClassesClassIdRoute: typeof ProtectedClassesClassIdRoute
  ProtectedCoursesCourseIdRoute: typeof ProtectedCoursesCourseIdRouteWithChildren
  ProtectedSubjectsSubjectIdRoute: typeof ProtectedSubjectsSubjectIdRoute
  ProtectedClassesIndexRoute: typeof ProtectedClassesIndexRoute
  ProtectedCoursesIndexRoute: typeof ProtectedCoursesIndexRoute
  ProtectedSubjectsIndexRoute: typeof ProtectedSubjectsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedTodosRoute: ProtectedTodosRoute,
  ProtectedClassesClassIdRoute: ProtectedClassesClassIdRoute,
  ProtectedCoursesCourseIdRoute: ProtectedCoursesCourseIdRouteWithChildren,
  ProtectedSubjectsSubjectIdRoute: ProtectedSubjectsSubjectIdRoute,
  ProtectedClassesIndexRoute: ProtectedClassesIndexRoute,
  ProtectedCoursesIndexRoute: ProtectedCoursesIndexRoute,
  ProtectedSubjectsIndexRoute: ProtectedSubjectsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  ResourcesRoute: ResourcesRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoOrpcTodoRoute: DemoOrpcTodoRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
